# Generated by Django 6.0.3 on 2026-03-24 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rolagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.CharField(default='Aventureiro', max_length=100)),
                ('tipo_dado', models.CharField(default='D20', max_length=10)),
                ('resultado', models.IntegerField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
