# Generated by Django 5.2.4 on 2026-06-04 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0007_remove_item_valor_item_raridade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolagem',
            options={},
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='privada',
        ),
        migrations.AddField(
            model_name='item',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personagem',
            name='vida_maxima',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='mestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas_mestrada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to='lobby.mesa'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personagens', to=settings.AUTH_USER_MODEL),
        ),
    ]
