# Generated by Django 5.2.4 on 2026-06-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0008_alter_rolagem_options_remove_mesa_privada_item_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
