# Generated by Django 5.2.4 on 2026-06-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0009_alter_item_ativo_alter_personagem_ativo'),
        ('lobby', '0010_criar_admin'),
    ]

    operations = [
    ]
