# Generated by Django 5.2.4 on 2026-06-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0011_merge_20260608_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='carisma',
            field=models.IntegerField(default=10, help_text='Persuasão, liderança e presença'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='condicoes',
            field=models.CharField(blank=True, help_text='Condições atuais: Envenenado, Paralisado, etc.', max_length=200),
        ),
        migrations.AddField(
            model_name='personagem',
            name='constituicao',
            field=models.IntegerField(default=10, help_text='Resistência, saúde e fortitude'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='destreza',
            field=models.IntegerField(default=10, help_text='Agilidade, reflexos e pontaria'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='forca',
            field=models.IntegerField(default=10, help_text='Força física, capacidade de dano e carga'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='inteligencia',
            field=models.IntegerField(default=10, help_text='Raciocínio, conhecimento e lógica'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='pontos_mana',
            field=models.IntegerField(default=0, help_text='Pontos de mana para magias'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='pontos_mana_maximo',
            field=models.IntegerField(default=0, help_text='Mana máxima'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='pontos_vida_temporarios',
            field=models.IntegerField(default=0, help_text='PV temporários (escudos, bênçãos)'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='sabedoria',
            field=models.IntegerField(default=10, help_text='Intuição, percepção e vontade'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='xp',
            field=models.IntegerField(default=0, help_text='Pontos de experiência'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='xp_proximo_nivel',
            field=models.IntegerField(default=300, help_text='XP necessário para o próximo nível'),
        ),
    ]
