# Generated by Django 5.2.4 on 2026-06-24 12:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0012_personagem_carisma_personagem_condicoes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Combate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="⚔️ Combate", max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                ("rodada", models.IntegerField(default=1)),
                ("turno_atual", models.IntegerField(default=0)),
                (
                    "data_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparando", "Preparando"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                        ],
                        default="preparando",
                        max_length=20,
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combates",
                        to="lobby.mesa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipanteCombate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("heroi", "Herói"),
                            ("monstro", "Monstro"),
                            ("npc", "NPC"),
                        ],
                        default="heroi",
                        max_length=20,
                    ),
                ),
                ("iniciativa", models.IntegerField(default=0)),
                ("ordem", models.IntegerField(default=0)),
                ("vivo", models.BooleanField(default=True)),
                ("vida_atual", models.IntegerField(default=10)),
                ("vida_maxima", models.IntegerField(default=10)),
                (
                    "condicao",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("envenenado", "Envenenado"),
                            ("paralisado", "Paralisado"),
                            ("confuso", "Confuso"),
                            ("cego", "Cego"),
                            ("surdo", "Surdo"),
                            ("assustado", "Assustado"),
                            ("invisivel", "Invisível"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("defesa", models.IntegerField(default=10)),
                (
                    "combate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participantes",
                        to="lobby.combate",
                    ),
                ),
                (
                    "personagem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lobby.personagem",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="AcaoCombate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.IntegerField()),
                ("turno", models.IntegerField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ataque", "Ataque"),
                            ("defesa", "Defesa"),
                            ("magia", "Magia"),
                            ("cura", "Cura"),
                            ("especial", "Especial"),
                            ("movimento", "Movimento"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
                ("alvo", models.CharField(blank=True, max_length=100, null=True)),
                ("resultado", models.TextField(blank=True, null=True)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "combate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acoes",
                        to="lobby.combate",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lobby.participantecombate",
                    ),
                ),
            ],
        ),
    ]
