# Generated by Django 5.2.4 on 2026-06-24 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0014_missao_missaopersonagem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("info", "Informação"),
                            ("sucesso", "Sucesso"),
                            ("alerta", "Alerta"),
                            ("perigo", "Perigo"),
                            ("missao", "Missão"),
                            ("combate", "Combate"),
                            ("sistema", "Sistema"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("lida", models.BooleanField(default=False)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("link_url", models.CharField(blank=True, max_length=500, null=True)),
                ("link_texto", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_criacao"],
            },
        ),
    ]
