# Generated by Django 5.2.4 on 2026-05-04 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_alter_rolagem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personagens', to='lobby.mesa'),
        ),
    ]
