# Generated by Django 6.0.4 on 2026-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_personagem_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
