# Generated by Django 6.0.4 on 2026-05-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0004_personagem_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolagem',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Rolagem de Dado', 'verbose_name_plural': 'Log de Rolagens'},
        ),
        migrations.AddField(
            model_name='mesa',
            name='privada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolagem',
            name='editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolagem',
            name='motivo_edicao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rolagem',
            name='resultado_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
