# Generated by Django 6.0.4 on 2026-05-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_alter_rolagem_options_mesa_privada_rolagem_editado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('peso', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('valor', models.IntegerField(default=0, help_text='Valor em moedas de ouro')),
            ],
        ),
        migrations.AddField(
            model_name='personagem',
            name='itens',
            field=models.ManyToManyField(blank=True, related_name='possuidores', to='lobby.item'),
        ),
    ]
