# Generated by Django 6.0.5 on 2026-05-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_item_personagem_itens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='valor',
        ),
        migrations.AddField(
            model_name='item',
            name='raridade',
            field=models.CharField(choices=[('Comum', 'Comum'), ('Incomum', 'Incomum'), ('Raro', 'Raro'), ('Épico', 'Épico'), ('Lendário', 'Lendário')], default='Comum', max_length=20),
        ),
    ]
