# Generated by Django 5.2.4 on 2026-06-24 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lobby", "0013_combate_participantecombate_acaocombate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Missao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "objetivos",
                    models.TextField(help_text="Descreva os objetivos da missão"),
                ),
                ("recompensa_xp", models.IntegerField(default=0)),
                ("recompensa_ouro", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("em_andamento", "Em Andamento"),
                            ("concluida", "Concluída"),
                            ("falha", "Falha"),
                        ],
                        default="disponivel",
                        max_length=20,
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_inicio", models.DateTimeField(blank=True, null=True)),
                ("data_conclusao", models.DateTimeField(blank=True, null=True)),
                (
                    "prazo",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data limite para concluir a missão",
                        null=True,
                    ),
                ),
                (
                    "dificuldade",
                    models.CharField(
                        choices=[
                            ("facil", "Fácil"),
                            ("medio", "Médio"),
                            ("dificil", "Difícil"),
                            ("epico", "Épico"),
                            ("lendario", "Lendário"),
                        ],
                        default="medio",
                        max_length=20,
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missoes",
                        to="lobby.mesa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MissaoPersonagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progresso",
                    models.IntegerField(
                        default=0, help_text="Progresso atual da missão (0-100)"
                    ),
                ),
                ("concluida", models.BooleanField(default=False)),
                ("data_conclusao", models.DateTimeField(blank=True, null=True)),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Notas do mestre sobre o progresso deste personagem",
                    ),
                ),
                (
                    "missao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progressos",
                        to="lobby.missao",
                    ),
                ),
                (
                    "personagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missoes",
                        to="lobby.personagem",
                    ),
                ),
            ],
            options={
                "unique_together": {("missao", "personagem")},
            },
        ),
    ]
